--드롭
--DROP TABLE MEMBER_LEVEL CASCADE CONSTRAINTS;
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
--멤버등급 테이블
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(10) NOT NULL
);
INSERT INTO MEMBER_LEVEL VALUES (-1, 'Black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;
--시퀀스
DROP SEQUENCE mNO_SQ;
CREATE SEQUENCE mNO_SQ
    MAXVALUE 9999   -- 최대값
    NOCYCLE         -- 순환방지(DEFAULT:CYCLE)
    NOCACHE;        -- 캐시메모리 사용 안 함
--멤버 테이블
CREATE TABLE MEMBER(
    mNO     NUMBER(5)       PRIMARY KEY,
    mNAME   VARCHAR2(15)    NOT NULL,
    mPW     VARCHAR2(8)     NOT NULL,
    mEMAIL  VARCHAR2(30)    UNIQUE,
    mPOINT  NUMBER(10)      CHECK(mPOINT>=0),
    mRDATE  DATE            DEFAULT SYSDATE,
    LEVELNO NUMBER(1)       REFERENCES MEMBER_LEVEL(LEVELNO)
);
SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES(mNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '24/09/26', 0);
INSERT INTO MEMBER VALUES(mNO_SQ.NEXTVAL, '신길동', 'bb', 'shin@shin.com', 0, '22/04/01', 1);
--출력
SELECT mNO "고객번호", mNAME "고객명", TO_CHAR(mRDATE, 'YYYY-MM-DD') "가입일", mEMAIL "이메일", mPOINT "포인트", LEVELNAME||'고객' "등급명"
    FROM MEMBER_LEVEL "ML", MEMBER
    WHERE MEMBER.LEVELNO = ML.LEVELNO;