-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도

DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ 
    START WITH 101  -- 101부터 생성(DEFAULT: 1)
    INCREMENT BY 1  -- 1씩 증가(DEFAULT: 1)
    MAXVALUE 9999   -- 최대값
    MINVALUE 0      -- 최소값(INCREMENT (-)일 경우 유효하겠지)
    NOCYCLE         -- 순환방지(DEFAULT:CYCLE)
    NOCACHE;         -- 캐시메모리 사용 안 함
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; -- NEXTVAL: 순차번호 생성, 실행할수록 진행 / DUAL: 오라클 제공 더미 테이블
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL: (생성 없이,) 현재까지 진행된 순차번호

-- EX. 시퀀스를 이용한 FRIEND 테이블
DROP TABLE FREIND;
CREATE TABLE FRIEND(
    NO          NUMBER(5)       PRIMARY KEY,
    NAME        VARCHAR2(30)    NOT NULL,
    TEL         VARCHAR2(20)    UNIQUE,
    ADDRESS     VARCHAR2(255)   ,
    LAST_MODIFY DATE            DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 9999 NOCACHE NOCYCLE;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번 실행 가능
SELECT NO, NAME, TEL, ADDRESS, TO_CHAR(LAST_MODIFY, 'RR/MM/DD AM HH:MI:SS') "LAST_MODIFY"
    FROM FRIEND;
INSERT INTO FRIEND
    VALUES (FRIEND_SQ.NEXTVAL, '고길동', '010-9999-8888', '봉천', SYSDATE);
    