"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

1. SECRET_KEY 처리(.env)
2. app 등록
3. myproject 밑에 templates 폴더(base.html, header.html, footer.html)와 static 폴더 추가 후 등록
4. (선택) 한국어 등록(admin 페이지)
5. 한국 timezone 등록
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # 내 프로젝트 ROOT
# print('프로젝트 루트 폴더:', BASE_DIR)
# print(os.path.join(BASE_DIR, 'myproject', 'templates'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

load_dotenv()
SECRET_KEY = os.getenv("SECRET_KEY", "myprojectsecretkey")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.0.227', '127.0.0.1', 'localhost'] # ip 통한 접근, local 접근
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1").split(',')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 생성한 app 등록
    "blog", 
    "accounts",
    "book",
    "django.contrib.humanize", # intcomma(세 자리마다 comma) 필터 사용
    "article", # GenericView 이용 - v1. paging 처리 / v2. 검색 기능  / v3. 파일 첨부(ch08)
    "filetest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ #templates 경로
            os.path.join(BASE_DIR, 'myproject', 'templates'), #C:\ai\source\12_django\myproject\myproject\templates
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = { # cmd: python manage.py migrate → db 적용 / python manage.py createsuperuser → superuser admin 생성
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr" # django admin 페이지 언어 default: "en-us"

TIME_ZONE = "Asia/Seoul" # default: "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 개발 환경 static
STATIC_URL = "static/" # app 폴더 밑의 static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myproject', 'static')
]

# 배포 후 운영 환경 static (later)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 업로드한 파일이 저장될 폴더와 액세스 url
# /media/folder/a.png url로 접근 => _media/folder/a.png저장
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "_media")
# myproject/urls.py에 MEDIA_URL와 ROOT연결